<?php if($page==='admin/categories'):?>
<div class="page-heading"><span class="eyebrow">KATALOĞUNU DÜZENLE</span><h1>Kategoriler</h1><p>Ürün eklerken bu kategoriler arasından seçim yapabilirsiniz. Kategori adını değiştirdiğinizde bağlı ürünler de güncellenir.</p></div>
<div class="panel"><?php startform('category_save','filters');?><label>Yeni kategori adı<input name="name" maxlength="60" required placeholder="Örneğin: Kulaklıklar"></label><button class="button dark">+ Kategori ekle</button><a class="button" href="<?=url('admin/edit')?>">+ Yeni ürün ekle</a></form></div>
<?php foreach(query('SELECT c.*, (SELECT COUNT(*) FROM products p WHERE p.category=c.name) AS total FROM categories c ORDER BY name')->fetchAll() as $c):?><div class="panel"><?php startform('category_save','filters');?><input type="hidden" name="id" value="<?=$c['id']?>"><label>Kategori adı<input name="name" value="<?=e($c['name'])?>" maxlength="60" required></label><span><?=$c['total']?> ürün</span><button class="button">Adı güncelle</button></form></div><?php endforeach?>
<?php else:?>
<div class="page-heading"><span class="eyebrow">SİTENİ KİŞİSELLEŞTİR</span><h1>Logo, isim ve renkler</h1><p>Kaydettiğiniz görünüm mağazada ve yönetim panelinde uygulanır.</p></div>
<form method="post" enctype="multipart/form-data" class="panel form-grid"><?=csrf()?><input type="hidden" name="action" value="branding">
<?php input('shop_name','Mağaza adı',shopName());?><img class="brand-preview" src="<?=e(shopLogo())?>" alt="Mevcut mağaza logosu"><label>Yeni logo (PNG, JPG, WebP · en fazla 5 MB)<input type="file" name="logo" accept="image/png,image/jpeg,image/webp"></label><label class="check"><input type="checkbox" name="reset_logo">Varsayılan logoya dön</label>
<h2>Renk paleti</h2><div class="color-grid"><?php $labels=['ink'=>'Yazı ve koyu düğmeler','teal'=>'Ana vurgu','sea'=>'İkinci vurgu','cream'=>'Bölüm zeminleri','paper'=>'Sayfa ve kart zemini','line'=>'Çizgiler','muted'=>'İkincil yazılar','mint'=>'Ürün ve arama zemini'];foreach(themeDefaults() as $key=>$default):?><label><?=e($labels[$key])?><input type="color" name="color_<?=$key?>" value="<?=e(setting('color_'.$key,$default))?>"></label><?php endforeach?></div><p class="muted">Yazı ve zemin renklerini okunabilir olacak şekilde farklı seçin.</p><button class="button dark">Görünümü kaydet</button></form>
<?php endif?>
