<?php if($page==='forgot'):?>
<div class="auth-panel"><h1>Şifremi unuttum</h1><p>Kayıtlı e-postanı yaz. Yenileme bağlantısı 30 dakika geçerli olacak.</p><?php startform('password_forgot','form-grid');input('email','E-posta','','email');?><button class="button dark">Yenileme bağlantısı iste</button></form></div>
<?php elseif($page==='reset'):?>
<div class="auth-panel"><h1>Yeni şifre belirle</h1><?php startform('password_reset','form-grid');?><input type="hidden" name="token" value="<?=e($_GET['token']??'')?>"><?php input('new_password','Yeni şifre (en az 12 karakter)','','password');input('confirm_password','Yeni şifre tekrar','','password');?><button class="button dark">Şifreyi yenile</button></form></div>
<?php else:?>
<div class="page-heading"><h1>Hesap güvenliği ve bildirimler</h1></div>
<?php startform('password_change','panel form-grid');input('current_password','Mevcut şifre','','password');input('new_password','Yeni şifre (en az 12 karakter)','','password');input('confirm_password','Yeni şifre tekrar','','password');?><button class="button dark">Şifremi değiştir</button></form>
<?php if(admin()):?><div class="panel"><h2>E-posta gönderimi</h2><p>Gönderen adresini Mağaza ve ödeme ekranında ayarlayın. Hosting zamanlanmış görevine app/mail-worker.php eklenmelidir. Sunucunun kabul ettiği ileti alıcıya ulaşmış sayılmaz; test mesajını gelen kutusunda doğrulayın.</p><?php startform('mail_test');?><button class="button">Yönetici adresime test iletisi sırala</button></form><p>Bekleyen: <?=query('SELECT COUNT(*) FROM mail_queue WHERE sent IS NULL AND attempts<5')->fetchColumn()?> · Başarısız: <?=query('SELECT COUNT(*) FROM mail_queue WHERE sent IS NULL AND attempts>=5')->fetchColumn()?></p></div><?php endif?>
<?php endif?>

<?php if($page==='admin/security'&&admin()):?><section class="panel"><h2>Google ve Apple ile giriş</h2><p>Alan adı ve sağlayıcı hesabı ayarlanmadan etkinleştirmeyin. Gizli anahtarlar tekrar gösterilmez; değiştirmiyorsanız boş bırakın.</p><?php startform('social_settings','form-grid');foreach(['google'=>'Google','apple'=>'Apple'] as $provider=>$label):?><h3><?=e($label)?></h3><?php input($provider.'_client_id',$label.' Client ID / Services ID',setting($provider.'_client_id'),'text',false);input($provider.'_client_secret',$label.' Client Secret'.($provider==='apple'?' (Apple özel anahtarıyla üretilmiş süreli JWT)':''),'','password',false);?><label class="check"><input type="checkbox" name="<?=$provider?>_login_enabled" <?=setting($provider.'_login_enabled')==='1'?'checked':''?>> <?=$label?> ile girişi etkinleştir</label><p>Dönüş adresi: <code><?=e(seoBase()?socialRedirect($provider):'Önce Mağaza ve ödeme bölümüne HTTPS alan adını girin.')?></code></p><?php endforeach?><p>Apple Client Secret süre dolmadan yenilenmelidir. Apple gizli e-posta yönlendirmesi için gönderen alan adını Apple panelinde tanımlayın.</p><button class="button dark">Giriş ayarlarını kaydet</button></form></section><?php endif?>
